### ISSUE TITLE
Exception: ('failed loading state dict!', './checkpoints/pifuhd.pt')

### ISSUE THREAD

**Issue by DingDongInUrMom** [facebookresearch/pifuhd#116]
I cannot get past the following code:

PS D:\PIFuHD\pifuhd> python -m apps.simple_test
Traceback (most recent call last):
  File "C:\Users\___________\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\___________\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\PIFuHD\pifuhd\apps\simple_test.py", line 30, in <module>
    reconWrapper(cmd, args.use_rect)
  File "D:\PIFuHD\pifuhd\apps\recon.py", line 220, in reconWrapper
    recon(opt, use_rect)
  File "D:\PIFuHD\pifuhd\apps\recon.py", line 163, in recon
    raise Exception('failed loading state dict!', state_dict_path)
Exception: ('failed loading state dict!', './checkpoints/pifuhd.pt')
PS D:\PIFuHD\pifuhd>

I assume it has something to do with the checkpoints directory, but I can't figure it out and I've tried several solutions. Including, but not limited to, looking through the issues threads, re-installing Python, installing Anaconda, googling for hours, and even YouTube videos covering PIFuHD. Only to come up with nothing.

**Comment by DingDongInUrMom** [comment]
Anyone know where to point me?

**Comment by manncodes** [comment]
Running the `download_trained_model.sh` will automatically make checkpoint directory.
Problem can bad file path in windows.
`download_trained_model.bat` for windows:
```cmd
@echo off
mkdir checkpointscd checkpointswget "https://dl.fbaipublicfiles.com/pifuhd/checkpoints/pifuhd.pt" pifuhd.pt
cd ..
```

**Comment by elduend3** [comment]
Are you trying to execute it from the home directory instead of the scripts directory?
I had the same message, but it was because I was on the /scripts folder

/GIT/pifuhd$ sh ./scripts/demo.sh

**Comment by Entretoize** [comment]
Did you find a solution ? I have the same problem...

**Comment by magnoborgo** [comment]
move the "checkpoint" directory to root (same place as "apps" , "scripts" directories")

**Comment by OvidWorks** [comment]
Hi, I have the same problem. I downloaded the pifuhd.pt manually, and put it in checkpoints folder in the root folder.
The Exception in line 163 is still raised. 
Thought that maybe pifuhd.pt is corrupted, I tried redownloading it with the same result...
