### ISSUE TITLE
glCheckError when running $sh ./scripts/demo.sh

### ISSUE THREAD

**Issue by HulkMaker** [facebookresearch/pifuhd#123]
File "/home/anaconda3/envs/ptgpu37/lib/python3.7/site-packages/OpenGL/error.py", line 234, in glCheckError
    baseOperation = baseOperation,
OpenGL.error.GLError: GLError(
	err = 1281,
	description = b'invalid value',
	baseOperation = glTexImage2D,
	pyArgs = (
		GL_TEXTURE_2D,
		0,
		GL_RGBA32F,
		512,
		512,
		0,
		GL_RGBA,
		GL_FLOAT,
		None,
	),
	cArgs = (
		GL_TEXTURE_2D,
		0,
		GL_RGBA32F,
		512,
		512,
		0,
		GL_RGBA,
		GL_FLOAT,
		None,
	),
	cArguments = (
		GL_TEXTURE_2D,
		0,
		GL_RGBA32F,
		512,
		512,
		0,
		GL_RGBA,
		GL_FLOAT,
		None,
	)
)

**Comment by Ranqing** [comment]
sample problem in macos. Is there any solution?

**Comment by enzyme69** [comment]
same issue in 2023, macOS

```
Compilation failure for vertex shader:
b"ERROR: 0:1: '' :  version '330' is not supported\nERROR: 0:1: '' : syntax error: #version\nERROR: 0:3: 'layout' : syntax error: syntax error\n"
Compilation failure for fragment shader:
b"ERROR: 0:1: '' :  version '330' is not supported\nERROR: 0:1: '' : syntax error: #version\n"
Linker failure: 
b'ERROR: One or more attached shaders not successfully compiled\n'
Traceback (most recent call last):
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/jimmygunawan/pifuhd/apps/render_turntable.py", line 69, in <module>
    renderer = ColorRender(width=args.width, height=args.height)
  File "/Users/jimmygunawan/pifuhd/lib/render/gl/color_render.py", line 34, in __init__
    CamRender.__init__(self, width, height, name, program_files=program_files)
  File "/Users/jimmygunawan/pifuhd/lib/render/gl/cam_render.py", line 32, in __init__
    Render.__init__(self, width, height, name, program_files, color_size, ms_rate)
  File "/Users/jimmygunawan/pifuhd/lib/render/gl/render.py", line 72, in __init__
    self.model_mat_unif = glGetUniformLocation(self.program, 'ModelMat')
  File "/Users/jimmygunawan/stable-diffusion-webui/env/lib/python3.9/site-packages/OpenGL/latebind.py", line 63, in __call__
    return self.wrapperFunction( self.baseFunction, *args, **named )
  File "/Users/jimmygunawan/stable-diffusion-webui/env/lib/python3.9/site-packages/OpenGL/GL/VERSION/GL_2_0.py", line 430, in glGetUniformLocation
    return baseOperation( program, name )
  File "/Users/jimmygunawan/stable-diffusion-webui/env/lib/python3.9/site-packages/OpenGL/platform/baseplatform.py", line 415, in __call__
    return self( *args, **named )
  File "/Users/jimmygunawan/stable-diffusion-webui/env/lib/python3.9/site-packages/OpenGL/error.py", line 230, in glCheckError
    raise self._errorClass(
OpenGL.error.GLError: GLError(
	err = 1282,
	description = b'invalid operation',
	baseOperation = glGetUniformLocation,
	cArguments = (3, b'ModelMat\x00'),
	result = -1
)

```

**Comment by mmmmmomo** [comment]
@enzyme69 
I got the same problem on centos8,it seems like the OPENGL version does not fits.
have you ever reslove it?

**Comment by JonathanLehner** [comment]
### this, why no solution?
