### ISSUE TITLE
Trying to run it locally on a non-CUDA gpu or just CPU

### ISSUE THREAD

**Issue by SomeAB** [facebookresearch/pifuhd#26]
I'm trying to run it on a local machine instead of the google collab demo

I have setup my local env, WSL2-Ubuntu, all required packages installed (and made sure to get a Pytorch+Pyvision version without CUDA) since I don't have a Nvidia GPU, rather a AMD Vega64. I also made sure my VcXsrv is working, by running the Xeyes program successfully.

I got this error initially: 

`Resuming from  ./checkpoints/pifuhd.pt
Traceback (most recent call last):
  File "/home/sunbath171/miniconda3/envs/my_env/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/sunbath171/miniconda3/envs/my_env/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/c/Users/Some Guy AB/Downloads/pifuhd-master/apps/simple_test.py", line 30, in <module>
    reconWrapper(cmd, args.use_rect)
  File "/mnt/c/Users/Some Guy AB/Downloads/pifuhd-master/apps/recon.py", line 220, in reconWrapper
    recon(opt, use_rect)
  File "/mnt/c/Users/Some Guy AB/Downloads/pifuhd-master/apps/recon.py", line 148, in recon
    state_dict = torch.load(state_dict_path)
  File "/home/sunbath171/.local/lib/python3.8/site-packages/torch/serialization.py", line 593, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/home/sunbath171/.local/lib/python3.8/site-packages/torch/serialization.py", line 773, in _legacy_load
    result = unpickler.load()
  File "/home/sunbath171/.local/lib/python3.8/site-packages/torch/serialization.py", line 729, in persistent_load
    deserialized_objects[root_key] = restore_location(obj, location)
  File "/home/sunbath171/.local/lib/python3.8/site-packages/torch/serialization.py", line 178, in default_restore_location
    result = fn(storage, location)
  File "/home/sunbath171/.local/lib/python3.8/site-packages/torch/serialization.py", line 154, in _cuda_deserialize
    device = validate_cuda_device(location)
  File "/home/sunbath171/.local/lib/python3.8/site-packages/torch/serialization.py", line 138, in validate_cuda_device
    raise RuntimeError('Attempting to deserialize object on a CUDA '
RuntimeError: Attempting to deserialize object on a CUDA device but torch.cuda.is_available() is False. If you are running on a CPU-only machine, please use torch.load with map_location=torch.device('cpu') to map your storages to the CPU.
Linker failure:

Linker failure:`

After that I changed this in recon.py : 
`state_dict = torch.load(state_dict_path, map_location=torch.device('cpu')) `

But I still get this error:
`Resuming from  ./checkpoints/pifuhd.pt
Warning: opt is overwritten.
test data size:  1
initialize network with normal
Traceback (most recent call last):
  File "/home/sunbath171/miniconda3/envs/my_env/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/sunbath171/miniconda3/envs/my_env/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/c/Users/Some Guy AB/Downloads/pifuhd-master/apps/simple_test.py", line 30, in <module>
    reconWrapper(cmd, args.use_rect)
  File "/mnt/c/Users/Some Guy AB/Downloads/pifuhd-master/apps/recon.py", line 220, in reconWrapper
    recon(opt, use_rect)
  File "/mnt/c/Users/Some Guy AB/Downloads/pifuhd-master/apps/recon.py", line 176, in recon
    netG = HGPIFuNetwNML(opt_netG, projection_mode).to(device=cuda)
  File "/home/sunbath171/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 443, in to
    return self._apply(convert)
  File "/home/sunbath171/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 203, in _apply
    module._apply(fn)
  File "/home/sunbath171/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 203, in _apply
    module._apply(fn)
  File "/home/sunbath171/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 225, in _apply
    param_applied = fn(param)
  File "/home/sunbath171/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 441, in convert
    return t.to(device, dtype if t.is_floating_point() else None, non_blocking)
  File "/home/sunbath171/.local/lib/python3.8/site-packages/torch/cuda/__init__.py", line 149, in _lazy_init
    _check_driver()
  File "/home/sunbath171/.local/lib/python3.8/site-packages/torch/cuda/__init__.py", line 47, in _check_driver
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
Linker failure:

Linker failure:

[]`

Need help figuring out the rest. I would ideally want to run it on my GPU. But as a last resort, I would be okay with running it on my CPU (i5 4670k) .. which is much much slower.

**Comment by shunsukesaito** [comment]
As the demo becomes extremely slow with cpu only, the current code base does not support cpu. However if you still wish to use only cpu, you may need to change this line https://github.com/facebookresearch/pifuhd/blob/a1559aee7f5e8584c94a74b50be29306481f4e06/apps/recon.py#L165

**Comment by SomeAB** [comment]
Is there a way to make it work with Vulkan or OpenCL? In near future @shunsukesaito

**Comment by SomeAB** [comment]
could something like this potentially work?
http://lernapparat.de/pytorch-rocm/

**Comment by shunsukesaito** [comment]
We don't plan to provide any solutions for Vulkan or OpenCL at this moment. You could potentially use these options at your own risk.

**Comment by SomeAB** [comment]
yeah, I totally understand. Its at my own risk only. Just asking whether the rocm solution listed on the blog.. according to your rough opinion, could it 'potentially' speaking work?

**Comment by shunsukesaito** [comment]
I have not personally tried this solution, but as the codebase only use pytorch buildin functions, if pytorch itself supports either vulkan or OpenCL, I can imagine this code should also work fine.

**Comment by SomeAB** [comment]
I'm still tinkering with it, will give you an update here, before closing.

**Comment by SomeAB** [comment]
Finally got it to work on a CPU, here are some of my observations in testing:

On an Intel i5 4670k, 16GB DDR3 RAM @ 1600Mhz, AMD Vega 64, HDD drive, Ubuntu 18.04, I used the default 512 resolution:

- Demo.sh ran on a .png file I added from internet in about 8-10 minutes average, taking 2-5 minutes more to finish up preparing the video+obj+png file. 

- I noticed a average of 14GB usage of RAM + 2GB of Swap. CPU usage was consistently 85-100%. 

- Progress bar doesn't update inbetween, goes directly from 0 to 100% on start->completion 

- I noticed a log of lag on the system even after the program has finished. Even simple task became much harder (even when system monitor is showing about 10-15% usage of CPU/RAM in total.

- Somehow, the program won't call the python packages installed inside the conda virtual environment, installed using conda (I initially installed all requirements using only conda, to avoid any conflict). When I created a pip virtual environement, and reinstalled everything using pip, it somehow worked. 

- btw, I tested with Pytorch 1.5.1 (which is the latest), noticed no issues on that part. 

Just trying to understand a few things here: 

Question1: Is Daniil Osokin's 'lightweight-human-pose-estimation' (that you used in google collab demo) a subset of Openpose? Used only to output the .json file ? 

Question2: The code after you clone 'lightweight-human-pose-estimation' is for cropping image besides keypoints? So input for your program has to be a human figure with background removed? 

Question 3: For lightweight-human-pose-estimation .. I tried using the demo sh file that came with it. I couldn't figure out the output folder for it, or how to pass the output parameter for it. How do I tell it .. where to output. I'm guessing you would know since you used it.

**Comment by denizkavzak** [comment]
> Finally got it to work on a CPU, here are some of my observations in initial testing:
> 
> On an Intel i5 4670k, 16GB DDR3 RAM @ 1600Mhz, AMD Vega 64, HDD drive, Ubuntu 18.04, I used the default 512 resolution:
> 
> * Demo.sh ran on a .png file I added from internet in about 8-10 minutes average, taking 2-5 minutes more to finish up preparing the video+obj+png file.
> * I noticed a average of 14GB usage of RAM + 2GB of Swap. CPU usage was consistently 85-100%.
> * Progress bar doesn't update inbetween, goes directly from 0 to 100% on start->completion
> * I noticed a lot of lag on the system even after the program was finished. Even simple task became much harder (even when system monitor is showing about 10-15% usage of CPU/RAM only in total).
> * Somehow, the program won't call the python packages installed inside the conda virtual environment, installed using conda (I initially installed all requirements using only conda, to avoid any conflict). When I created a pip virtual environement, and reinstalled everything using pip, it somehow worked.
> * btw, I tested with Pytorch 1.5.1 (which is the latest), noticed no issues on that part.
> 
> Just trying to understand a few things here:
> 
> Question1: Is Daniil Osokin's 'lightweight-human-pose-estimation' (that you used in google collab demo) a subset of Openpose? Used only to output the .json file ?
> 
> Question2: The code used after you clone 'lightweight-human-pose-estimation' (on google collab) is also for cropping image besides keypoints? So input for your program has to be a human figure with background removed - strictly or ideally or optionally?
> 
> Question 3: For lightweight-human-pose-estimation .. I tried using the demo sh file that came with it. I couldn't figure out the output folder for it, or how to pass the output parameter for it. How do I tell it .. where to output. I'm guessing you would know since you used it.
> 
> Question 4: What are the supported video formats currently? I'm guessing only .mp4?
> 
> Question 5: What are your future plans with this? From where I'm seeing it, it would become a great tool if implemented into blender (even as it is right now) .. given the code is re-written on a much lower level by blender devs.

Could you share the changes you made to make it run on CPU?

**Comment by shunsukesaito** [comment]
>Question1: Is Daniil Osokin's 'lightweight-human-pose-estimation' (that you used in google collab demo) a subset of Openpose? Used only to output the .json file ?
>Question2: The code used after you clone 'lightweight-human-pose-estimation' (on google collab) is also for cropping image besides keypoints? So input for your program has to be a human figure with background removed - strictly or ideally or optionally?
>Question 3: For lightweight-human-pose-estimation .. I tried using the demo sh file that came with it. I couldn't figure out the output folder for it, or how to pass the output parameter for it. How do I tell it .. where to output. I'm guessing you would know since you used it.

I offer two ways of cropping input image to be fed into PIFuHD. One way is to provide openpose estimation ({file_name}_keypoints.json). This way, the code automatically figures out how to crop the input images so that the proportion of body size in the image is roughly aligned with the training data. The other way is to directly provide bounding box info ({file_name}_rect.txt). The colab demo with lightweight-human-pose estimation dumps out this rect file in the same folder. These files should be placed under the same directory where input images are located.

>Question 4: What are the supported video formats currently? I'm guessing only .mp4?

The current demo supports only image files (JPEG and PNG). If you wish to process video files, you have to manually extract each frames as individual image files.

>Question 5: What are your future plans with this? From where I'm seeing it, it would become a great tool if implemented into blender (even as it is right now) .. given the code is re-written on a much lower level by blender devs.

The primary focus of this repository is to let researchers have access to runnable demo of PIFuHD to facilitate future research (notice that the code is released under non-commercial license).

**Comment by SomeAB** [comment]
@denizkavzak 

My solution is not perfect yet, but its near. As apparent from shunsuke's reply, I need to add the pose/cropping mechanism coming from openpose/light-weight-humanpose 

Here are a few things to do to get upto the mark:
- In apps/recon.py file .. change the line 148 & 165:

`state_dict = torch.load(state_dict_path) `  to `state_dict = torch.load(state_dict_path, map_location=torch.device('cpu'))`

`cuda = torch.device('cuda:%d' % opt.gpu_id)` to `cuda = torch.device('cpu')`

for trimesh .. install 'pip3 install trimesh[all]'

Try to install everything using `pip3` and not `conda`

Also, don't forget to put Python3 as your default Python. I tested this app with Python 3.6.x, but do have Python2 installed as well. I noticed that one of the dependencies looks for Python2 & not Python3. 



@shunsukesaito 
Q1. Okay, so JPEG files strictly need to have a .jpeg file extension or .jpg format would work as well? How does the code know to look for JPEG instead of PNG? I noticed (correct me if I'm wrong) that it merely looks into the 'samples images' folder. 

Q2. How to process multiple images? Do I need to run the code manually for each, or can the code take care of it?

Q3. So the actual cropping takes place where? Inside pifuhd code, or before it? 

Suggestion: for dependencies, I tested that 'python-opencv' package rather then 'opencv-python' worked for me. In the case of later, it kept giving me cv2 not found error. It would be beneficial if you could cross check on your side and update the list of dependencies accordingly.

Also, as stated to the other person, I clearly noticed that one of the dependencies works correctly when installed with 'pip install XXX' rather than 'pip3 install XXX'. I don't remember which one though.

**Comment by shunsukesaito** [comment]
>Q1. Okay, so JPEG files strictly need to have a .jpeg file extension or .jpg format would work as well? How does the code know to look for JPEG instead of PNG? I noticed (correct me if I'm wrong) that it merely looks into the 'samples images' folder.

png, jpeg, jpg are all supported. For actual implementation, please refer to ./lib/data/EvalDataset.py and ./lib/data/EvalWPoseDataset.py.

>Q2. How to process multiple images? Do I need to run the code manually for each, or can the code take care of it?

The demo script processes all images under the same directory as long as you also provide "keypoints.json" or "rect.txt". You don't need to specify individual image files.

>Q3. So the actual cropping takes place where? Inside pifuhd code, or before it?

Please take a look at 
https://github.com/facebookresearch/pifuhd/blob/a1559aee7f5e8584c94a74b50be29306481f4e06/lib/data/EvalDataset.py#L93
for rectangle file, and 
https://github.com/facebookresearch/pifuhd/blob/a1559aee7f5e8584c94a74b50be29306481f4e06/lib/data/EvalWPoseDataset.py#L244
for openpose json file.

**Comment by mogocat** [comment]
> As the demo becomes extremely slow with cpu only, the current code base does not support cpu. However if you still wish to use only cpu, you may need to change this line
> 
> https://github.com/facebookresearch/pifuhd/blob/a1559aee7f5e8584c94a74b50be29306481f4e06/apps/recon.py#L165

change to what?

**Comment by NicolasGoeddel** [comment]
I got it to run only on CPU but it consumes up to 14 GB of memory. If anyone is interested, I can share all the changes I had to do to make it work. I even created an `install.sh` script which clones all the stuff, downloads the pretrained nets and and can then be run with a single `run.sh` script and an image as parameter. Before I can share it with you, I have to refactor it a bit a test it again on a virgin system.

**Comment by SomeAB** [comment]
Do post it here, after you refactor it.

**Comment by NicolasGoeddel** [comment]
> Do post it here, after you refactor it.

I took a while to find all the culprits but it works now, even on my old Ubuntu Server 16.04.5. Here is the script:
https://gist.github.com/NicolasGoeddel/f809779f02167c565af3457a217b7e42

Without parameters it clones this repository into the subdirectory `pifuhd`, checks for some packages, creates a virtual environment, installs dependencies, downloads the pretrained nets and creates a simple `run.sh` script.

I can not test it on other distributions than Ubuntu, so maybe some package names could be different in your case.

**Comment by jfcostta** [comment]
@NicolasGoeddel and @denizkavzak 

I've submitted a pull request (#65) to support CPU only processing, you may find my forked source here
[(https://github.com/jfcostta/pifuhd)]

It's a very clean solution, once you've already managed how to install pytorch-cpu.

**Comment by SomeAB** [comment]
I have not given up on this, I will review this hopefully when I get better and have some time in the coming weeks. I have just recovered from a COVID19 infection. I hope Almighty keeps you all safe and healthy as well. Take care.

**Comment by jfcostta** [comment]
@SomeAB wish you a full recovery! Take your time, our health is what matters most.

**Comment by Chen0729** [comment]
Hi, @shunsukesaito Regarding running with multiple images from different view, how shall I specify the image name, if my image name is 0.png and 1.png, how shall I put the image path please ? thanks

**Comment by shunsukesaito** [comment]
> w shall I put the image path please ? thanks

Please create another issue for different topic. Regarding the question, unfortunately the released model does not support multi-view image inputs.

**Comment by DUMBANIKET** [comment]
> > Do post it here, after you refactor it.
> 
> It took a while to find all the culprits but it works now, even on my old Ubuntu Server 16.04.5. Here is the script:
> https://gist.github.com/NicolasGoeddel/f809779f02167c565af3457a217b7e42
> 
> Without parameters it clones this repository into the subdirectory `pifuhd`, checks for some packages, creates a virtual environment, installs dependencies, downloads the pretrained nets and creates a simple `run.sh` script.
> 
> I can not test it on other distributions than Ubuntu, so maybe some package names could be different in your case.

Can I just run it on a vm of ubuntu , and could u share the code as well :)

**Comment by SomeAB** [comment]
> > > Do post it here, after you refactor it.
> > 
> > 
> > It took a while to find all the culprits but it works now, even on my old Ubuntu Server 16.04.5. Here is the script:
> > https://gist.github.com/NicolasGoeddel/f809779f02167c565af3457a217b7e42
> > Without parameters it clones this repository into the subdirectory `pifuhd`, checks for some packages, creates a virtual environment, installs dependencies, downloads the pretrained nets and creates a simple `run.sh` script.
> > I can not test it on other distributions than Ubuntu, so maybe some package names could be different in your case.
> 
> Can I just run it on a vm of ubuntu , and could u share the code as well :)

All the answer are here already. See specifically the post above: https://github.com/facebookresearch/pifuhd/issues/26#issuecomment-654148472

Also, yes you can run it in a vm of ubuntu .. try using either Hyper-V or Vmware workstation player.. not sure which one is faster between the two, but its much faster then VirtualBox VMs 

If you spend some money, you could even run it in azure/aws or even a paid version of google collab

**Comment by DUMBANIKET** [comment]
![image](https://user-images.githubusercontent.com/111189215/281043811-fd561597-a82d-4668-80de-3e9b800cc0f6.png)
@NicolasGoeddel 
i have some issue (im not good at ai/ml stuffs) , so as per my case im using  an ubuntu 20 server with 16 gigs of ram and activated the virtual environment manually and all the packages are install properly though i think something is messed :)
