### ISSUE TITLE
error CuDNN

### ISSUE THREAD

**Issue by KKiohd** [facebookresearch/pifuhd#54]
I got this error

(base) D:\pifuhd>python -m apps.simple_test
Resuming from  ./checkpoints/pifuhd.pt
Warning: opt is overwritten.
test data size:  1
initialize network with normal
initialize network with normal
generate mesh (test) ...
  0%|                                                                                            | 0/1 [00:00<?, ?it/s]./results/pifuhd_final/recon/result_test_512.obj
  0%|                                                                                            | 0/1 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "D:\Mini-tutorial\miniconda\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Mini-tutorial\miniconda\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\pifuhd\apps\simple_test.py", line 30, in <module>
    reconWrapper(cmd, args.use_rect)
  File "D:\pifuhd\apps\recon.py", line 220, in reconWrapper
    recon(opt, use_rect)
  File "D:\pifuhd\apps\recon.py", line 210, in recon
    gen_mesh(opt.resolution, netMR, cuda, test_data, save_path, components=opt.use_compose)
  File "D:\pifuhd\apps\recon.py", line 38, in gen_mesh
    net.filter_global(image_tensor_global)
  File "D:\pifuhd\lib\model\HGPIFuMRNet.py", line 83, in filter_global
    self.netG.filter(images)
  File "D:\pifuhd\lib\model\HGPIFuNetwNML.py", line 122, in filter
    self.nmlF = self.netF.forward(images).detach()
  File "D:\pifuhd\lib\networks.py", line 163, in forward
    return self.model(input)
  File "D:\Mini-tutorial\miniconda\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\Mini-tutorial\miniconda\lib\site-packages\torch\nn\modules\container.py", line 117, in forward
    input = module(input)
  File "D:\Mini-tutorial\miniconda\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "D:\Mini-tutorial\miniconda\lib\site-packages\torch\nn\modules\conv.py", line 419, in forward
    return self._conv_forward(input, self.weight)
  File "D:\Mini-tutorial\miniconda\lib\site-packages\torch\nn\modules\conv.py", line 415, in _conv_forward
    return F.conv2d(input, weight, self.bias, self.stride,
RuntimeError: cuDNN error: CUDNN_STATUS_ALLOC_FAILED

(base) D:\pifuhd>python -m apps.render_turntable -f ./results/pifuhd_final/recon -ww 512 -hh 512
Traceback (most recent call last):
  File "D:\Mini-tutorial\miniconda\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Mini-tutorial\miniconda\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\pifuhd\apps\render_turntable.py", line 69, in <module>
    renderer = ColorRender(width=args.width, height=args.height)
  File "D:\pifuhd\lib\render\gl\color_render.py", line 34, in __init__
    CamRender.__init__(self, width, height, name, program_files=program_files)
  File "D:\pifuhd\lib\render\gl\cam_render.py", line 32, in __init__
    Render.__init__(self, width, height, name, program_files, color_size, ms_rate)
  File "D:\pifuhd\lib\render\gl\render.py", line 41, in __init__
    glutInit()
  File "D:\Mini-tutorial\miniconda\lib\site-packages\OpenGL\GLUT\special.py", line 333, in glutInit
    _base_glutInit( ctypes.byref(count), holder )
  File "D:\Mini-tutorial\miniconda\lib\site-packages\OpenGL\platform\baseplatform.py", line 423, in __call__
    raise error.NullFunctionError(
OpenGL.error.NullFunctionError: Attempt to call an undefined function glutInit, check for bool(glutInit) before calling

**Comment by shunsukesaito** [comment]
If this is cuDNN error, very likely it's a pytorch issue not pifuhd implementation. You can check if the same error is observed with any other pytorch example code that runs model on GPU.

**Comment by hfarhidzadeh** [comment]
@KKiohd Had this problem. Be sure pytorch, cuDNN, gpu driver and rest are compatible. It is frustrating to figure it out.
