### ISSUE TITLE
can't run locally

### ISSUE THREAD

**Issue by xAi2x** [facebookresearch/pifuhd#81]
I have tried for hours now. But i get the same error locally on the command "sh ./scripts/demo.sh" 

C:\Users\pette\Desktop\pifuhd-master>sh ./scripts/demo.sh
Traceback (most recent call last):
  File "C:\Users\pette\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\pette\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\pette\Desktop\pifuhd-master\apps\simple_test.py", line 30, in <module>
    reconWrapper(cmd, args.use_rect)
  File "C:\Users\pette\Desktop\pifuhd-master\apps\recon.py", line 220, in reconWrapper
    recon(opt, use_rect)
  File "C:\Users\pette\Desktop\pifuhd-master\apps\recon.py", line 163, in recon
    raise Exception('failed loading state dict!', state_dict_path)
Exception: ('failed loading state dict!', './checkpoints/pifuhd.pt')
Traceback (most recent call last):
  File "C:\Users\pette\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\pette\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\pette\Desktop\pifuhd-master\apps\render_turntable.py", line 69, in <module>
    renderer = ColorRender(width=args.width, height=args.height)
  File "C:\Users\pette\Desktop\pifuhd-master\lib\render\gl\color_render.py", line 34, in __init__
    CamRender.__init__(self, width, height, name, program_files=program_files)
  File "C:\Users\pette\Desktop\pifuhd-master\lib\render\gl\cam_render.py", line 32, in __init__
    Render.__init__(self, width, height, name, program_files, color_size, ms_rate)
  File "C:\Users\pette\Desktop\pifuhd-master\lib\render\gl\render.py", line 41, in __init__
    glutInit()
  File "C:\Users\pette\AppData\Local\Programs\Python\Python38\lib\site-packages\OpenGL\GLUT\special.py", line 333, in glutInit
    _base_glutInit( ctypes.byref(count), holder )
  File "C:\Users\pette\AppData\Local\Programs\Python\Python38\lib\site-packages\OpenGL\platform\baseplatform.py", line 423, in __call__
    raise error.NullFunctionError(
OpenGL.error.NullFunctionError: Attempt to call an undefined function glutInit, check for bool(glutInit) before calling

**Comment by hfarhidzadeh** [comment]
@DoubleTPeter How did you fix this? `OpenGL.error.NullFunctionError: Attempt to call an undefined function glutInit, check for bool(glutInit) before calling

`

**Comment by DoubleTPeter** [comment]
@hfarhidzadeh I found this tutorial. And just followed it with every step: https://www.youtube.com/watch?v=zzgCoyYyuN0&ab_channel=bycloudump
